## Generated by `nfl shim` from util.nfl -- do not edit.
import std/os
import nfl/compiler
export compiler
const nflSource = parentDir(currentSourcePath()) / "util.nfl"
nflModule(staticRead(nflSource), nflSource, autoloadCore = true)
