## Generated by `lfn shim` from util.lfn -- do not edit.
import std/os
import lfn/compiler
export compiler
const lfnSource = parentDir(currentSourcePath()) / "util.lfn"
lfnModule(staticRead(lfnSource), lfnSource, autoloadCore = true)
