## The `nfl` command-line entry point: parses `run`/`compile`/`check`/
## `macroexpand`/`shim`/`repl` invocations, drives the Nim compiler over a
## generated wrapper for `run`/`compile`/`check`, drives the macro expander
## directly for `macroexpand`, writes a Nim-importable delegation module for
## `shim`, and hands off to `repl.nim` for `repl`. See `man/cli.md` for the
## full command/flag reference.

import std/cmdline
import std/os
import std/osproc
import std/rdstdin
import std/strutils
import std/times

import ./compiler
import ./diagnostics
import ./reader
import ./repl
import ./syntax

type
  Command = enum
    cmdRun = "run"
    cmdCompile = "compile"
    cmdCheck = "check"
    cmdMacroexpand = "macroexpand"
    cmdShim = "shim"
    cmdRepl = "repl"

  CliOptions = object
    command: Command
    autoloadCore: bool
    emitNim: bool
    force: bool
    input: string
    inputDisplay: string
    outPath: string
    nimArgs: seq[string]

  ParseResult = object
    ok: bool
    exitCode: int
    showUsage: bool
    errorMessage: string
    options: CliOptions

const shimHeaderPrefix = "## Generated by `nfl shim` from "

proc nimStringLit(s: string): string =
  result = "\""
  for c in s:
    case c
    of '\\': result.add "\\\\"
    of '"': result.add "\\\""
    of '\n': result.add "\\n"
    of '\r': result.add "\\r"
    of '\t': result.add "\\t"
    else: result.add c
  result.add '"'

proc usage() =
  stderr.writeLine "usage: nfl <run|compile|check> [--no-core] [--emit nim] file.nfl [-- nim-args...]"
  stderr.writeLine "       nfl <macroexpand|shim> [--no-core] [--out path] [--force] file.nfl"
  stderr.writeLine "       nfl repl [--no-core] [file.nfl]"
  stderr.writeLine "Args after -- are passed straight through to the underlying `nim` invocation" &
    " (run/compile/check only), e.g. `nfl compile file.nfl -- --mm:orc -d:release`."

proc parseCommand(value: string): Command =
  case value
  of "run": cmdRun
  of "compile": cmdCompile
  of "check": cmdCheck
  of "macroexpand": cmdMacroexpand
  of "shim": cmdShim
  of "repl": cmdRepl
  else:
    raise newException(ValueError, "unknown command: " & value)

proc fail(msg: string): ParseResult =
  ParseResult(ok: false, exitCode: 2, showUsage: true, errorMessage: msg)

proc parseOptions(args: seq[string]): ParseResult =
  if args.len == 0:
    return ParseResult(ok: false, exitCode: 2, showUsage: true)
  if args[0] in ["-h", "--help"]:
    return ParseResult(ok: false, exitCode: 0, showUsage: true)

  try:
    result.options.command = parseCommand(args[0])
  except ValueError:
    return ParseResult(ok: false, exitCode: 2, showUsage: true)

  result.options.autoloadCore = true
  var inputArg = ""
  var i = 1
  while i < args.len:
    let arg = args[i]
    if arg == "--":
      if result.options.command notin {cmdRun, cmdCompile, cmdCheck}:
        return fail("nfl: -- (nim arg passthrough) is only valid with run/compile/check")
      result.options.nimArgs = args[i + 1 .. ^1]
      i = args.len
    elif arg == "--no-core":
      result.options.autoloadCore = false
      inc i
    elif arg == "--force":
      result.options.force = true
      inc i
    elif arg == "--emit" or arg.startsWith("--emit="):
      if result.options.command == cmdMacroexpand:
        return fail("nfl: --emit is not valid with macroexpand")
      if result.options.command == cmdRepl:
        return fail("nfl: --emit is not valid with repl")
      var value: string
      if arg.startsWith("--emit="):
        value = arg["--emit=".len .. ^1]
        inc i
      else:
        if i + 1 >= args.len:
          return fail("nfl: --emit requires a value")
        value = args[i + 1]
        i += 2
      if value != "nim":
        return fail("nfl: unknown --emit value: " & value)
      result.options.emitNim = true
    elif arg == "--out" or arg.startsWith("--out="):
      if result.options.command != cmdShim:
        return fail("nfl: --out is only valid with shim")
      var value: string
      if arg.startsWith("--out="):
        value = arg["--out=".len .. ^1]
        inc i
      else:
        if i + 1 >= args.len:
          return fail("nfl: --out requires a value")
        value = args[i + 1]
        i += 2
      result.options.outPath = value
    elif arg.len > 0 and arg.startsWith("-"):
      return fail("nfl: unknown flag: " & arg)
    else:
      if inputArg.len != 0:
        return ParseResult(ok: false, exitCode: 2, showUsage: true)
      inputArg = arg
      inc i

  if result.options.force and result.options.command != cmdShim:
    return fail("nfl: --force is only valid with shim")

  if result.options.command == cmdRepl:
    # `repl` takes an optional positional (a file to preload into the
    # session) rather than a required one.
    result.ok = true
    if inputArg.len > 0:
      result.options.inputDisplay = inputArg
      result.options.input = absolutePath(inputArg)
    return result

  if inputArg.len == 0:
    return ParseResult(ok: false, exitCode: 2, showUsage: true)

  result.ok = true
  result.options.inputDisplay = inputArg
  result.options.input = absolutePath(inputArg)

proc repoSrcPath(): string =
  let candidate = getCurrentDir() / "src"
  if dirExists(candidate / "nfl"):
    absolutePath(candidate)
  else:
    ""

proc defaultOutputPath(input: string): string =
  changeFileExt(input, ExeExt)

proc tempBuildDir(): string =
  getTempDir() / ("nfl-" & $getCurrentProcessId() & "-" & $epochTime())

proc wrapperSource(input: string; autoloadCore: bool; emitNim: bool): string =
  "import nfl/compiler\n" &
    "nflModule(staticRead(" & nimStringLit(input) & "), " &
    nimStringLit(input) & ", autoloadCore = " & $autoloadCore &
    ", emitNim = " & $emitNim & ")\n"

proc runNim(args: seq[string]): int =
  let nimExe = findExe("nim")
  if nimExe.len == 0:
    stderr.writeLine "nfl: nim executable not found in PATH"
    return 1
  let process = startProcess(nimExe, args = args, options = {poParentStreams})
  result = process.waitForExit()
  process.close()

proc nimArgsFor(options: CliOptions; wrapper: string): seq[string] =
  case options.command
  of cmdRun:
    result.add @["c", "-r"]
  of cmdCompile:
    result.add "c"
    result.add "--out:" & defaultOutputPath(options.input)
  of cmdCheck:
    result.add "check"
  of cmdMacroexpand, cmdShim, cmdRepl:
    discard

  let srcPath = repoSrcPath()
  if srcPath.len > 0:
    result.add "--path:" & srcPath
  result.add options.nimArgs
  result.add wrapper

proc macroexpand(options: CliOptions): int =
  try:
    for form in expandSource(readFile(options.input), options.input, options.autoloadCore):
      stdout.writeLine form.renderSyntax()
    0
  except ReaderError as err:
    stderr.writeLine $err.diagnostic
    1
  except CompilerError as err:
    stderr.writeLine $err.diagnostic
    1

proc compileViaNim(options: CliOptions): int =
  let tempDir = tempBuildDir()
  createDir(tempDir)
  let wrapper = tempDir / "wrapper.nim"
  writeFile(wrapper, wrapperSource(options.input, options.autoloadCore, options.emitNim))

  result = runNim(nimArgsFor(options, wrapper))
  if result == 0:
    removeDir(tempDir)
  else:
    stderr.writeLine "nfl: preserved temporary build directory: " & tempDir

proc shimSource(input: string): string =
  ## Generates a Nim module that delegates to `nflModule` to compile `input`
  ## at Nim compile time, so plain Nim code can `import` an NFL module
  ## without going through the `nfl` CLI. See `man/package-layout.md` for
  ## the package layout this is meant to fit into.
  shimHeaderPrefix & input.extractFilename() & " -- do not edit.\n" &
    "import std/os\n" &
    "import nfl/compiler\n" &
    "export compiler\n" &
    "const nflSource = parentDir(currentSourcePath()) / " & nimStringLit(input.extractFilename()) & "\n" &
    "nflModule(staticRead(nflSource), nflSource, autoloadCore = true)\n"

proc writeShim(options: CliOptions): int =
  let outPath =
    if options.outPath.len > 0: absolutePath(options.outPath)
    else: changeFileExt(options.input, ".nim")

  if fileExists(outPath) and not options.force:
    let existing = readFile(outPath)
    let firstLine = existing.splitLines()[0]
    if not firstLine.startsWith(shimHeaderPrefix):
      stderr.writeLine "nfl: refusing to overwrite non-generated file: " & outPath
      return 1

  writeFile(outPath, shimSource(options.input))
  0

proc replReadLine(prompt: string; line: var string): bool =
  readLineFromStdin(prompt, line)

proc printReplHelp() =
  stdout.writeLine "REPL commands:"
  stdout.writeLine "  :help        show this help"
  stdout.writeLine "  :quit, :exit quit the REPL"
  stdout.writeLine "  :transcript  print the accumulated session source"
  stdout.writeLine "  :reset       clear the session"

proc loadReplFile(session: var ReplSession; options: CliOptions): int =
  ## Preloads `options.input` (the `repl` command's optional positional) as
  ## a single transcript entry before the interactive loop starts. See
  ## `man/repl.md` for why a whole file is one entry rather than one per
  ## top-level form.
  if not fileExists(options.input):
    stderr.writeLine "nfl: file not found: " & options.inputDisplay
    return 1
  var source = readFile(options.input)
  while source.len > 0 and source[^1] in {'\n', '\r'}:
    source.setLen(source.len - 1)
  var forms: seq[Syntax]
  try:
    forms = readAll(source, options.input)
  except ReaderError as err:
    stderr.writeLine $err.diagnostic
    return 1
  if forms.len == 0:
    return 0
  let outcome = session.tryAddInput(source, forms)
  case outcome.outcome
  of aoAdded:
    stdout.write outcome.message
    0
  of aoError:
    stderr.writeLine outcome.message
    1
  of aoSkippedDefvar, aoBlank:
    0

proc runRepl(options: CliOptions): int =
  var session = initSession(options.autoloadCore)
  defer: closeSession(session)

  if options.input.len > 0:
    let loadResult = loadReplFile(session, options)
    if loadResult != 0:
      return loadResult

  while true:
    let read = readEntry(replReadLine, "nfl> ", "  ... ")
    case read.outcome
    of roEof:
      break
    of roBlank:
      continue
    of roError:
      stderr.writeLine read.message
      continue
    of roForm:
      if read.forms.len == 0:
        # The first line started with `:` — a REPL command, not NFL source.
        case read.source
        of ":help":
          printReplHelp()
        of ":quit", ":exit":
          break
        of ":transcript":
          stdout.write session.transcriptText()
        of ":reset":
          closeSession(session)
          session = initSession(options.autoloadCore)
        else:
          stderr.writeLine "nfl repl: unknown command: " & read.source
      else:
        let outcome = session.tryAddInput(read.source, read.forms)
        case outcome.outcome
        of aoAdded:
          stdout.write outcome.message
        of aoSkippedDefvar, aoBlank:
          discard
        of aoError:
          stderr.writeLine outcome.message
  0

proc main(): int =
  let parsed = parseOptions(commandLineParams())
  if not parsed.ok:
    if parsed.errorMessage.len > 0:
      stderr.writeLine parsed.errorMessage
    if parsed.showUsage:
      usage()
    return parsed.exitCode

  let options = parsed.options

  if options.command == cmdRepl:
    return runRepl(options)

  if not fileExists(options.input):
    stderr.writeLine "nfl: file not found: " & options.inputDisplay
    return 1

  case options.command
  of cmdMacroexpand:
    macroexpand(options)
  of cmdShim:
    writeShim(options)
  of cmdRun, cmdCompile, cmdCheck:
    compileViaNim(options)
  of cmdRepl:
    0  # unreachable — handled above

when isMainModule:
  quit main()
