## The `nfl` command-line entry point: parses `run`/`compile`/`check`/
## `macroexpand`/`shim` invocations, drives the Nim compiler over a generated
## wrapper for `run`/`compile`/`check`, drives the macro expander directly
## for `macroexpand`, and writes a Nim-importable delegation module for
## `shim`. See `man/cli.md` for the full command/flag reference.

import std/cmdline
import std/os
import std/osproc
import std/strutils
import std/times

import ./compiler
import ./diagnostics
import ./syntax

type
  Command = enum
    cmdRun = "run"
    cmdCompile = "compile"
    cmdCheck = "check"
    cmdMacroexpand = "macroexpand"
    cmdShim = "shim"

  CliOptions = object
    command: Command
    autoloadCore: bool
    emitNim: bool
    force: bool
    input: string
    inputDisplay: string
    outPath: string

  ParseResult = object
    ok: bool
    exitCode: int
    showUsage: bool
    errorMessage: string
    options: CliOptions

const shimHeaderPrefix = "## Generated by `nfl shim` from "

proc nimStringLit(s: string): string =
  result = "\""
  for c in s:
    case c
    of '\\': result.add "\\\\"
    of '"': result.add "\\\""
    of '\n': result.add "\\n"
    of '\r': result.add "\\r"
    of '\t': result.add "\\t"
    else: result.add c
  result.add '"'

proc usage() =
  stderr.writeLine "usage: nfl <run|compile|check|macroexpand|shim> [--no-core] [--emit nim] [--out path] [--force] file.nfl"

proc parseCommand(value: string): Command =
  case value
  of "run": cmdRun
  of "compile": cmdCompile
  of "check": cmdCheck
  of "macroexpand": cmdMacroexpand
  of "shim": cmdShim
  else:
    raise newException(ValueError, "unknown command: " & value)

proc fail(msg: string): ParseResult =
  ParseResult(ok: false, exitCode: 2, showUsage: true, errorMessage: msg)

proc parseOptions(args: seq[string]): ParseResult =
  if args.len == 0:
    return ParseResult(ok: false, exitCode: 2, showUsage: true)
  if args[0] in ["-h", "--help"]:
    return ParseResult(ok: false, exitCode: 0, showUsage: true)

  try:
    result.options.command = parseCommand(args[0])
  except ValueError:
    return ParseResult(ok: false, exitCode: 2, showUsage: true)

  result.options.autoloadCore = true
  var inputArg = ""
  var i = 1
  while i < args.len:
    let arg = args[i]
    if arg == "--no-core":
      result.options.autoloadCore = false
      inc i
    elif arg == "--force":
      result.options.force = true
      inc i
    elif arg == "--emit" or arg.startsWith("--emit="):
      if result.options.command == cmdMacroexpand:
        return fail("nfl: --emit is not valid with macroexpand")
      var value: string
      if arg.startsWith("--emit="):
        value = arg["--emit=".len .. ^1]
        inc i
      else:
        if i + 1 >= args.len:
          return fail("nfl: --emit requires a value")
        value = args[i + 1]
        i += 2
      if value != "nim":
        return fail("nfl: unknown --emit value: " & value)
      result.options.emitNim = true
    elif arg == "--out" or arg.startsWith("--out="):
      if result.options.command != cmdShim:
        return fail("nfl: --out is only valid with shim")
      var value: string
      if arg.startsWith("--out="):
        value = arg["--out=".len .. ^1]
        inc i
      else:
        if i + 1 >= args.len:
          return fail("nfl: --out requires a value")
        value = args[i + 1]
        i += 2
      result.options.outPath = value
    elif arg.len > 0 and arg.startsWith("-"):
      return fail("nfl: unknown flag: " & arg)
    else:
      if inputArg.len != 0:
        return ParseResult(ok: false, exitCode: 2, showUsage: true)
      inputArg = arg
      inc i

  if result.options.force and result.options.command != cmdShim:
    return fail("nfl: --force is only valid with shim")

  if inputArg.len == 0:
    return ParseResult(ok: false, exitCode: 2, showUsage: true)

  result.ok = true
  result.options.inputDisplay = inputArg
  result.options.input = absolutePath(inputArg)

proc repoSrcPath(): string =
  let candidate = getCurrentDir() / "src"
  if dirExists(candidate / "nfl"):
    absolutePath(candidate)
  else:
    ""

proc defaultOutputPath(input: string): string =
  changeFileExt(input, ExeExt)

proc tempBuildDir(): string =
  getTempDir() / ("nfl-" & $getCurrentProcessId() & "-" & $epochTime())

proc wrapperSource(input: string; autoloadCore: bool; emitNim: bool): string =
  "import nfl/compiler\n" &
    "nflModule(staticRead(" & nimStringLit(input) & "), " &
    nimStringLit(input) & ", autoloadCore = " & $autoloadCore &
    ", emitNim = " & $emitNim & ")\n"

proc runNim(args: seq[string]): int =
  let nimExe = findExe("nim")
  if nimExe.len == 0:
    stderr.writeLine "nfl: nim executable not found in PATH"
    return 1
  let process = startProcess(nimExe, args = args, options = {poParentStreams})
  result = process.waitForExit()
  process.close()

proc nimArgsFor(options: CliOptions; wrapper: string): seq[string] =
  case options.command
  of cmdRun:
    result.add @["c", "-r"]
  of cmdCompile:
    result.add "c"
    result.add "--out:" & defaultOutputPath(options.input)
  of cmdCheck:
    result.add "check"
  of cmdMacroexpand, cmdShim:
    discard

  let srcPath = repoSrcPath()
  if srcPath.len > 0:
    result.add "--path:" & srcPath
  result.add wrapper

proc macroexpand(options: CliOptions): int =
  try:
    for form in expandSource(readFile(options.input), options.input, options.autoloadCore):
      stdout.writeLine form.renderSyntax()
    0
  except ReaderError as err:
    stderr.writeLine $err.diagnostic
    1
  except CompilerError as err:
    stderr.writeLine $err.diagnostic
    1

proc compileViaNim(options: CliOptions): int =
  let tempDir = tempBuildDir()
  createDir(tempDir)
  let wrapper = tempDir / "wrapper.nim"
  writeFile(wrapper, wrapperSource(options.input, options.autoloadCore, options.emitNim))

  result = runNim(nimArgsFor(options, wrapper))
  if result == 0:
    removeDir(tempDir)
  else:
    stderr.writeLine "nfl: preserved temporary build directory: " & tempDir

proc shimSource(input: string): string =
  ## Generates a Nim module that delegates to `nflModule` to compile `input`
  ## at Nim compile time, so plain Nim code can `import` an NFL module
  ## without going through the `nfl` CLI. See `man/package-layout.md` for
  ## the package layout this is meant to fit into.
  shimHeaderPrefix & input.extractFilename() & " -- do not edit.\n" &
    "import std/os\n" &
    "import nfl/compiler\n" &
    "export compiler\n" &
    "const nflSource = parentDir(currentSourcePath()) / " & nimStringLit(input.extractFilename()) & "\n" &
    "nflModule(staticRead(nflSource), nflSource, autoloadCore = true)\n"

proc writeShim(options: CliOptions): int =
  let outPath =
    if options.outPath.len > 0: absolutePath(options.outPath)
    else: changeFileExt(options.input, ".nim")

  if fileExists(outPath) and not options.force:
    let existing = readFile(outPath)
    let firstLine = existing.splitLines()[0]
    if not firstLine.startsWith(shimHeaderPrefix):
      stderr.writeLine "nfl: refusing to overwrite non-generated file: " & outPath
      return 1

  writeFile(outPath, shimSource(options.input))
  0

proc main(): int =
  let parsed = parseOptions(commandLineParams())
  if not parsed.ok:
    if parsed.errorMessage.len > 0:
      stderr.writeLine parsed.errorMessage
    if parsed.showUsage:
      usage()
    return parsed.exitCode

  let options = parsed.options

  if not fileExists(options.input):
    stderr.writeLine "nfl: file not found: " & options.inputDisplay
    return 1

  case options.command
  of cmdMacroexpand:
    macroexpand(options)
  of cmdShim:
    writeShim(options)
  of cmdRun, cmdCompile, cmdCheck:
    compileViaNim(options)

when isMainModule:
  quit main()
